services:
  - type: web
    name: watchora-scraper-server
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /health
